

exports.tasksPage = function(tarefas,data){
    
    var pagHtml=`<!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Management</title>
        </head>
        <body>
                <header class="w3-container w3-teal">
                    <h1>Task Manager</h1>
                </header>
            <div class="element">
            <div>
                <table class="w3-table w3-striped" style="width:40%">
                    <tr><th>TO DO<th></tr>
    `
    for(let i=0;i<tarefas.length;i++){
        if(tarefas[i].done=="0"){
            pagHtml+=`
                <tr>
                            <td>
                                <label>Task: <b>${tarefas[i].description}</b> by <b>${tarefas[i].user}</b> until <b>${tarefas[i].duedate}</b></label>
                            </td>
                            <td>
                                <input class="w3-check" type="checkbox" name="${tarefas[i].id}" value="${tarefas[i].done}"/>
                            </td>
                </tr>
                `
        }
    }
    pagHtml+=`</table>
            </div">
                    <table class="w3-table w3-striped" style="width:40%">
                    <tr><th>DONE<th></tr>
    `
    for(let i=0;i<tarefas.length;i++){
        if(tarefas[i].done=="1"){
            pagHtml+=`
                <tr>
                            <td>
                                <label>Task: <b>${tarefas[i].description}</b> by <b>${tarefas[i].user}</b> until <b>${tarefas[i].duedate}</b></label>
                            </td>
                            <td>
                                <input class="w3-check" type="checkbox" name="${tarefas[i].id}" value="${tarefas[i].done}" checked/>
                            </td>
                </tr>
                `
        }
    }
    pagHtml+=`  </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2023 in ${data}</h5>
                </footer>
        </body>
        </html>`
    return pagHtml
}

exports.errorPage = function(errorMessage,d){
    return `<p>Error: Date:${d} Message:${errorMessage}</p>`
}